"""
LLM-backed paper write-up — generates the Discussion and Implications from
the *real* tool outputs and provenance, rather than pasting pre-written
domain templates.

This is A.M.Y's implementation of the Sakana AI Scientist v2 manuscript
write-up step (arXiv:2504.08066, Fig. 1: "Manuscript Template → Manuscript"):
the manuscript prose is generated by an LLM conditioned on the structured
experimental outputs, not assembled from a fixed `DOMAIN_INSIGHTS` dictionary.

Design constraints (so this strengthens rather than weakens the project):
- **Grounding.** The model is given only the actual tool results (descriptions
  + output text, which are the same strings hashed into provenance.json). It is
  instructed to discuss *only* numbers that appear in that context and never to
  invent values. NOTE on the downstream check: `NumericVerifier` does NOT
  re-check *every* number — it pattern-matches only clinical-style statistics
  (p-values, HR/OR/RR with CI, median survival, 95% CI ranges, clinical-context
  percentages) and flags those that lack nearby provenance. A hallucinated
  *non-clinical* quantity (a bare energy, slope, ratio, prime count) is NOT
  automatically flagged. So grounding here rests primarily on the prompt
  constraint and low temperature, not on an exhaustive numeric gate; treat the
  LLM Discussion as provenance-conditioned, not provenance-verified.
- **Falls back silently.** Any error (no API key, timeout, malformed JSON)
  returns ``None`` so the caller keeps the deterministic template output. The
  template path remains the default; the LLM path is opt-in via
  ``AMY_USE_LLM_ENHANCER=1``.
- **Reproducibility.** Temperature is low and the topic+results form the only
  conditioning, so re-runs are stable enough for an auditable pipeline.

Enable with::

    AMY_USE_LLM_ENHANCER=1
    AMY_ENHANCER_MODEL=glm-5.1   # optional; defaults to config.yaml llm.reasoner
"""
from __future__ import annotations

import json
import math
import os
import re

import structlog

log = structlog.get_logger()


def llm_enhancer_enabled() -> bool:
    return os.getenv("AMY_USE_LLM_ENHANCER", "").lower() in ("1", "true", "yes")


def _resolve_model() -> str:
    model = os.getenv("AMY_ENHANCER_MODEL")
    if model:
        return model
    try:
        import yaml
        cfg_path = os.path.join(os.path.dirname(__file__), "..", "config.yaml")
        with open(cfg_path) as f:
            cfg = yaml.safe_load(f) or {}
        return cfg.get("llm", {}).get("reasoner", {}).get("model", "glm-5.1")
    except Exception:
        return "glm-5.1"


def _build_client():
    """Construct an OllamaCloudClient with base_url from config.yaml."""
    from core.ollama_client import OllamaCloudClient
    cfg = {"base_url": "https://ollama.com/api"}
    try:
        import yaml
        cfg_path = os.path.join(os.path.dirname(__file__), "..", "config.yaml")
        with open(cfg_path) as f:
            full = yaml.safe_load(f) or {}
        if full.get("llm", {}).get("base_url"):
            cfg["base_url"] = full["llm"]["base_url"]
    except Exception:
        pass
    return OllamaCloudClient(cfg)


def _format_results_context(results: list[dict], limit: int = 12) -> str:
    """Render tool results as a compact, grounded evidence block.

    Only the description + result text are exposed — exactly the strings that
    are hashed into provenance — so the model cannot ground a claim in anything
    that is not in the audit trail.
    """
    lines = []
    for i, r in enumerate(results[:limit], 1):
        tool = r.get("tool", "unknown")
        desc = r.get("description", "").strip()
        result_text = str(r.get("result", "")).strip()
        # Keep each result bounded while preserving fit metrics and audit hashes
        # from compact scientific tools such as huckel_polyene_scaling.
        if len(result_text) > 2000:
            result_text = result_text[:2000] + " …[truncated]"
        eid = r.get("experiment_id")
        header = f"[E{i}] tool=`{tool}`"
        if eid:
            header += f"  (experiment_id: {eid})"
        block = header
        if desc:
            block += f"\n  description: {desc}"
        if result_text:
            block += f"\n  output: {result_text}"
        lines.append(block)
    return "\n\n".join(lines)


def _format_hypotheses(hypotheses: list[dict]) -> str:
    if not hypotheses:
        return "(none generated)"
    out = []
    for i, h in enumerate(hypotheses, 1):
        status = h.get("novelty_status", "unknown")
        conf = h.get("confidence", 0.5)
        out.append(f"H{i} [{status}, confidence {conf:.0%}]: {h.get('hypothesis','')}")
    return "\n".join(out)


def _decimal_claims(text: str) -> list[str]:
    return [
        raw.replace("−", "-")
        for raw in re.findall(r"[-−]?\d+\.\d+(?:[eE][+-]?\d+)?", text or "")
    ]


def _evidence_decimal_values(results: list[dict]) -> tuple[str, list[float]]:
    evidence_text = "\n".join(str(r.get("result", "")) for r in results)
    values = []
    for token in _decimal_claims(evidence_text):
        try:
            values.append(float(token))
        except ValueError:
            continue
    return evidence_text, values


def _decimal_is_grounded(token: str, evidence_text: str, evidence_values: list[float]) -> bool:
    if token in evidence_text:
        return True
    if re.search(re.escape(token) + r"\d*", evidence_text):
        return True
    try:
        value = float(token)
    except ValueError:
        return False
    return any(math.isclose(value, known, rel_tol=5e-4, abs_tol=5e-6) for known in evidence_values)


def _drop_unsupported_numeric_sentences(content: str, results: list[dict]) -> tuple[str, list[str]]:
    """Remove LLM sentences that introduce decimal claims absent from evidence."""
    evidence_text, evidence_values = _evidence_decimal_values(results)
    if not evidence_text:
        return content, []

    unsupported = [
        token
        for token in _decimal_claims(content)
        if not _decimal_is_grounded(token, evidence_text, evidence_values)
    ]
    if not unsupported:
        return content, []

    unsupported_set = set(unsupported)
    cleaned_paragraphs = []
    for paragraph in content.split("\n\n"):
        sentences = re.split(r"(?<=[.!?])\s+", paragraph)
        kept = [
            sentence
            for sentence in sentences
            if sentence and not any(token in sentence for token in unsupported_set)
        ]
        if kept:
            cleaned_paragraphs.append(" ".join(kept))

    cleaned = "\n\n".join(cleaned_paragraphs).strip()
    return cleaned, list(dict.fromkeys(unsupported))


_PROCESS_PREAMBLE_RE = re.compile(
    r"^\s*(?:let me|i(?:'ll| will| need to)|we need to)\b"
    r".*\b(?:analy[sz]e|write|draft|craft|produce|prepare|discuss)\b",
    re.IGNORECASE,
)


def _strip_process_preamble(content: str) -> tuple[str, list[str]]:
    """Remove model process chatter that does not belong in manuscript prose."""
    lines = content.strip().splitlines()
    removed = []
    while lines and _PROCESS_PREAMBLE_RE.search(lines[0].strip()):
        removed.append(lines.pop(0).strip())
        while lines and not lines[0].strip():
            lines.pop(0)
    return "\n".join(lines).strip(), removed


DISCUSSION_SYSTEM = (
    "You are a careful computational scientist writing the Discussion section "
    "of a research paper. You write in precise, sober academic prose. You are "
    "rigorously honest: you distinguish verification of known results from "
    "genuine novelty, you never overstate, and you explicitly note when a "
    "result is a finite-range or single-method observation rather than a proven "
    "claim."
)

DISCUSSION_PROMPT = """Write the Discussion section for a computational paper in the domain of **{domain}** on the topic: "{topic}".

You are given the COMPLETE set of computational evidence below. This is the only evidence that exists for this paper.

EVIDENCE (each block is a real tool execution; every number shown is recorded in a cryptographically hashed provenance file):
{results_context}

CANDIDATE HYPOTHESES already generated for this paper (ranked):
{hypotheses}

STRICT RULES:
1. Discuss ONLY numbers that appear verbatim in the EVIDENCE above. Do NOT invent, round differently, or extrapolate numerical values. If you want to mention a quantity, it must be copied from the evidence.
2. Distinguish honestly between (a) reproducing a known/textbook result, (b) a finite-range or single-method observation, and (c) a genuinely novel candidate finding. Most computational verification falls in (a) or (b); say so plainly.
3. If all evidence comes from one underlying tool/method, state that this is internal consistency, NOT methodological independence or cross-validation.
4. Consider at least one alternative explanation or limitation (e.g. floating-point artifacts, finite sample size, lack of observational data) for the main result.
5. Do NOT fabricate citations. Do not include a reference list (it is added separately).
6. Do NOT compute new predicted values for future experiments. Future-work paragraphs may name the next variable or limit qualitatively, but must not include a new decimal prediction unless that exact decimal appears in EVIDENCE.
7. Write 3-6 substantive paragraphs. Use Markdown. You may use **bold** subheadings per theme. End with a short **Implications** paragraph that states what new, testable question the evidence motivates — grounded in the actual results, not generic boilerplate.

Return ONLY the Discussion section text (Markdown). Do not add a "## Discussion" heading — start directly with the prose."""


async def generate_discussion_llm(
    domain: str,
    topic: str,
    results: list[dict],
    hypotheses: list[dict] | None = None,
    client=None,
    model: str | None = None,
    timeout: float = 90.0,
    feedback: str | None = None,
    belief_confidence: float | None = None,
) -> str | None:
    """Generate a provenance-grounded Discussion section via the LLM.

    ``feedback`` (optional) is the Meta-review agent's synthesized digest of
    recurring weaknesses from prior papers (see ``cognition.meta_review_agent``).
    When provided — or present in the ``AMY_METAREVIEW_FEEDBACK`` env var — it is
    appended to the prompt so the model pre-empts mistakes that kept recurring.
    This is the Co-Scientist feedback-propagation loop closing into the write-up.

    ``belief_confidence`` (optional, 0..1) is the world-model's *re-estimated*
    reliability of the belief types behind these results, learned from prior
    cycles' confirm/contradict evidence (see ``evolution.self_retrain`` and the
    learning-ablation ``weights`` arm). When provided — or present in the
    ``AMY_BELIEF_CONFIDENCE`` env var — it calibrates how firmly vs. tentatively
    the model is told to state findings: low learned reliability → hedge more and
    foreground limitations; high → state findings more firmly. This is the
    parameter-update (weight) learning path closing into the write-up, distinct
    from the prompt-feedback path above.

    Returns the Markdown string, or ``None`` on any failure so the caller can
    fall back to the deterministic template. Returns ``None`` (not an empty
    discussion) when there are no usable results to ground on.
    """
    grounded = [r for r in (results or []) if str(r.get("result", "")).strip()]
    if not grounded:
        return None

    if client is None:
        try:
            client = _build_client()
        except Exception as exc:
            log.info("llm_enhancer.no_client", error=str(exc))
            return None

    model = model or _resolve_model()
    prompt = DISCUSSION_PROMPT.format(
        domain=domain,
        topic=topic,
        results_context=_format_results_context(grounded),
        hypotheses=_format_hypotheses(hypotheses or []),
    )

    # Meta-review feedback injection (explicit arg wins over env channel).
    fb = feedback if feedback is not None else os.getenv("AMY_METAREVIEW_FEEDBACK", "")
    if fb and fb.strip():
        prompt += (
            "\n\n---\n"
            "Additionally, apply this feedback learned from prior review cycles "
            "(it lists recurring weaknesses to avoid — it does NOT override the "
            "grounding rules above):\n\n" + fb.strip()
        )
        log.info("llm_enhancer.feedback_injected", chars=len(fb))

    # Learned belief-confidence injection (explicit arg wins over env channel).
    # Mirrors the feedback path: a real parameter update (the world-model's
    # re-estimated reliability) closing into the write-up. It calibrates tone
    # only — it does NOT override the grounding rules above.
    bc_raw = belief_confidence if belief_confidence is not None else os.getenv("AMY_BELIEF_CONFIDENCE")
    if bc_raw is not None and str(bc_raw).strip() != "":
        try:
            bc = max(0.0, min(1.0, float(bc_raw)))
        except (TypeError, ValueError):
            bc = None
        if bc is not None:
            if bc < 0.4:
                stance = (
                    "LOW: the underlying belief types have been unreliable in prior "
                    "cycles. State findings tentatively, foreground limitations and "
                    "alternative explanations, and avoid firm claims."
                )
            elif bc < 0.7:
                stance = (
                    "MODERATE: treat findings as provisional — state them plainly but "
                    "with explicit caveats about their finite-range / single-method scope."
                )
            else:
                stance = (
                    "HIGH: the underlying belief types have been reliable in prior "
                    "cycles. You may state well-supported findings more firmly, while "
                    "still distinguishing reproduction from genuine novelty."
                )
            prompt += (
                "\n\n---\n"
                f"Calibration: the world-model's learned reliability of the belief "
                f"types behind this evidence is {bc:.2f} (0 = unreliable, 1 = "
                f"reliable), re-estimated from prior cycles' confirm/contradict "
                f"evidence. Calibrate how firmly vs. tentatively you state findings "
                f"accordingly — {stance} This affects tone only; it does NOT relax "
                f"the grounding rules above."
            )
            log.info("llm_enhancer.belief_confidence_injected", confidence=round(bc, 4))

    messages = [
        {"role": "system", "content": DISCUSSION_SYSTEM},
        {"role": "user", "content": prompt},
    ]

    # think=False: glm-class thinking models otherwise spend the whole
    # num_predict budget on their hidden trace and return empty/short content
    # (this caused a biology paper to fall back to a stub Discussion that then
    # carried an ungrounded number). Retry once before giving up; returning None
    # falls the caller back to the deterministic — and grounded — template.
    import asyncio
    last_exc = None
    for attempt in range(2):
        try:
            resp = await asyncio.wait_for(
                client.chat(model=model, messages=messages, temperature=0.3,
                            max_tokens=2048, think=False),
                timeout=timeout,
            )
            content = (resp.get("message", {}) or {}).get("content", "").strip()
            if not content:
                content = (resp.get("message", {}) or {}).get("thinking", "").strip()
            if content.startswith("```"):
                content = content.strip("`")
                if content.lower().startswith("markdown"):
                    content = content[len("markdown"):].lstrip()
            content, removed_preamble = _strip_process_preamble(content)
            if removed_preamble:
                log.info(
                    "llm_enhancer.process_preamble_removed",
                    count=len(removed_preamble),
                    examples=removed_preamble[:2],
                )
            if len(content) < 120:
                log.info("llm_enhancer.too_short", length=len(content), attempt=attempt)
                if attempt == 0:
                    await asyncio.sleep(1.5)
                    continue
                return None
            content, removed_decimals = _drop_unsupported_numeric_sentences(content, grounded)
            if removed_decimals:
                log.info(
                    "llm_enhancer.numeric_sentences_removed",
                    count=len(removed_decimals),
                    decimals=removed_decimals[:12],
                )
            if len(content) < 120:
                log.info("llm_enhancer.too_short_after_numeric_sanitizer",
                         length=len(content), attempt=attempt)
                if attempt == 0:
                    await asyncio.sleep(1.5)
                    continue
                return None
            log.info("llm_enhancer.discussion_generated", model=model, chars=len(content))
            return content
        except Exception as exc:
            last_exc = exc
            if attempt == 0:
                await asyncio.sleep(1.5)
    log.warning("llm_enhancer.generation_failed", error=str(last_exc), model=model)
    return None
